"""Jeu de données de départ — séance 1, exercice 1.2."""

EDITEURS_INITIAUX = [
    {"nom": "Team Cherry", "pays": "Australie"},
    {"nom": "ConcernedApe", "pays": "États-Unis"},
    {"nom": "Maddy Makes Games", "pays": "Canada"},
    {"nom": "Innersloth", "pays": "États-Unis"},
    {"nom": "Supergiant Games", "pays": "États-Unis"},
    {"nom": "Toby Fox", "pays": "États-Unis"},
    {"nom": "Valve", "pays": "États-Unis"},
    {"nom": "ZA/UM", "pays": "Estonie"},
]

JEUX_INITIAUX = [
    {
        "titre": "Hollow Knight",
        "genre": "Metroidvania",
        "note": 9,
        "annee": 2017,
        "tags": ["indé", "difficile"],
        "code_editeur": "TCH-2017",
        "editeur": "Team Cherry",
    },
    {
        "titre": "Stardew Valley",
        "genre": "Simulation",
        "note": 8,
        "annee": 2016,
        "tags": ["indé", "détente"],
        "code_editeur": "CAP-2016",
        "editeur": "ConcernedApe",
    },
    {
        "titre": "Celeste",
        "genre": "Plateforme",
        "note": 9,
        "annee": 2018,
        "tags": ["indé", "difficile"],
        "code_editeur": "MMG-2018",
        "editeur": "Maddy Makes Games",
    },
    {
        "titre": "Among Us",
        "genre": "Party",
        "note": 6,
        "annee": 2018,
        "tags": ["multijoueur"],
        "code_editeur": "INN-2018",
        "editeur": "Innersloth",
    },
    {
        "titre": "Hades",
        "genre": "Roguelike",
        "note": 9,
        "annee": 2020,
        "tags": ["indé", "action"],
        "code_editeur": "SGG-2020",
        "editeur": "Supergiant Games",
    },
    {
        "titre": "Undertale",
        "genre": "RPG",
        "note": 8,
        "annee": 2015,
        "tags": ["indé", "narratif"],
        "code_editeur": "TFX-2015",
        "editeur": "Toby Fox",
    },
    {
        "titre": "Portal 2",
        "genre": "Réflexion",
        "note": 10,
        "annee": 2011,
        "tags": ["coopératif"],
        "code_editeur": "VLV-2011",
        "editeur": "Valve",
    },
    {
        "titre": "Disco Elysium",
        "genre": "RPG",
        "note": 9,
        "annee": 2019,
        "tags": ["narratif"],
        "code_editeur": "ZAU-2019",
        "editeur": "ZA/UM",
    },
]
